### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by Keepinmindy** [TheNoiselessNoise/google_play_achievement_unlocker#1]
Hey again, thanks you for redirecting me to your github.

So I have some issues, I don't know if it's because a ran a system cleanup with SD Maid Pro but since the first initial installation were everything seemed to work fine now some commands are just not working anymore.

First here is what I do when I enter to Termux, tell me if I miss something :
 
"tsu"
"cd /sdcard"
"cd gpau/"

Then when I type :

"python gpau.py --list-cc"

I get a blank line, but if I type :

"python gpau.py --list-games"

I can see my games, do you know why I don't see something when I do the "--list-cc" command ?

I have another issue with nicecli.py, when I do :

"python nicecli.py"

I get an error : 

"Traceback (most recent call last):
File "/storage/emulated/0/gpau/nicecli.py", line 6, in <module> from terminaltables import AsciiTable
ModuleNotFoundError : No module named 'terminaltables'

If you could help me with this I would really appreciate.

**Comment by TheNoiselessNoise** [comment]
Ok, if you don't see anything in "--list-cc" that's because you need to first run the games and login to Google Play account inside them. There are games that won't appear at all and you can run [python gpau.py --readme] to get a list of things you can try.

"--list-games" just prints all registered games from the time you logged into an account on your device

If you are missing a terminaltables module, just run [pip install terminaltables] and you should be good.

**Comment by TheNoiselessNoise** [comment]
Ok, if you don't see anything in `--list-cc` that's because you need to first run the games and login to Google Play account inside them. There are games that won't appear at all and you can run `python gpau.py --readme` to get a list of things you can try.

`--list-games` just prints all installed games

If you are missing a terminaltables module, just run `pip install terminaltables` and you should be good.

**Comment by Keepinmindy** [comment]
"pip install terminaltables" command is giving me error :     

------------------------------------------------------------------------------------------------

WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/

Could not fetch URL https://pypi.org/simple/terminaltables/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/terminaltables/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

ERROR: Could not find a version that satisfies the requirement terminaltables (from versions: none)

ERROR: No matching distribution found for terminaltables

------------------------------------------------------------------------------------------------

Also "--list-cc" is still giving me a blank line even tho I installed a new game and unlocked achievement, "--list-games " is working fine however.

**Comment by TheNoiselessNoise** [comment]
It looks like you are missing OpenSSL package, so install it with command.
`pkg install openssl`

And it would be good to upgrade pip if needed.
`python -m pip install --upgrade pip`

If --list-cc is still empty i guess you need to try and try.

Also, if you have multiple accounts, maybe you are using bad account for GPAU.
You can list players.
`python gpau.py --list-players`

Then every command extend with:
`-p <number_of_player>`

For example:
`python gpau.py --list-cc -p 1`

**Comment by Keepinmindy** [comment]
Thank you so much I managed to fix all the issues, is there anything I can do to remove a player with your commands ? I already removed it through the android system in google settings but it's still here in termux.

**Comment by TheNoiselessNoise** [comment]
You could try to remove/rename the .db file of the player.

Path to the .db files:
`/data/data/com.google.android.gms/databases/<your_db_file>`

If you `--list-players` you can get the filename of the player you want to remove.

Then you just remove:
`tsu`
`rm /data/data/com.google.android.gms/databases/<your_db_file>`

Or rename:
`tsu`
`mv /data/data/com.google.android.gms/databases/<your_db_file> /some/path/<your_db_file>`
